# Generated by Django 6.0.5 on 2026-05-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_client_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeownerprofile',
            name='alt_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
