# Generated by Django 6.0.5 on 2026-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Credit/Debit Card'), ('cash', 'Cash on Delivery')], default='cash', max_length=20),
        ),
    ]
