# Generated by Django 6.0.5 on 2026-05-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_initial'),
        ('store', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.store'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
