# Generated by Django 6.0.5 on 2026-05-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_store_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Outbound SMS Log',
                'verbose_name_plural': 'Outbound SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
