# Generated by Django 6.0.5 on 2026-06-04 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_outboundsmslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('category_ids', models.JSONField(blank=True, null=True)),
                ('brand_ids', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversations', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversations', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Bot Conversation',
                'verbose_name_plural': 'Bot Conversations',
            },
        ),
    ]
