# Generated by Django 6.0.5 on 2026-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_botconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all_seasons', 'All Seasons')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('linen', 'Linen'), ('wool', 'Wool'), ('leather', 'Leather')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_range',
            field=models.CharField(blank=True, choices=[('budget', 'Budget'), ('value', 'Value'), ('standard', 'Standard'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='fabric',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='cost_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
