# Generated by Django on 2026-06-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_add_training_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('normalized_term', models.CharField(max_length=100, unique=True)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_keywords', to='store.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_keywords', to='store.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_keywords', to='store.product')),
            ],
            options={
                'ordering': ['-last_seen'],
                'verbose_name': 'Learned Keyword',
                'verbose_name_plural': 'Learned Keywords',
            },
        ),
        migrations.AddField(
            model_name='botconversation',
            name='message_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='response_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botconversation',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
