# Generated by Django 4.2.7 on 2026-06-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_allow_guest_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Credit/Debit Card'), ('cash', 'Pay on delivery/pickup')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_awaiting', 'Payment awaiting confirmation'), ('paid', 'Paid'), ('packing', 'Packing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('cleared', 'Cleared from cashier'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
