# Generated by Django 4.2.7 on 2026-06-18 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalyticReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('baseline_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reset_at', models.DateTimeField(auto_now=True)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
