# Generated by Django 4.2.7 on 2026-06-18 15:25

from django.db import migrations, models
from django.utils.text import slugify


CORE_FILTER_SLUGS = {'tops', 'bottoms', 'shoes', 'accessories'}


def seed_product_subcategories(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    ProductSubcategory = apps.get_model('store', 'ProductSubcategory')
    for name in Product.objects.exclude(subcategory='').values_list('subcategory', flat=True).distinct():
        name = (name or '').strip()
        subcategory_slug = slugify(name).strip('-')
        if not name or not subcategory_slug or subcategory_slug in CORE_FILTER_SLUGS:
            continue
        ProductSubcategory.objects.get_or_create(
            slug=subcategory_slug,
            defaults={'name': name},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Subcategory',
                'verbose_name_plural': 'Product Subcategories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_product_subcategories, migrations.RunPython.noop),
    ]
