# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_notes',
            field=models.TextField(blank=True),
        ),
    ]
