# Generated by Django 4.2.7 on 2026-06-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_initial'),
        ('store', '0027_product_publication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending fulfillment'), ('ready', 'Ready for payout'), ('paid', 'Paid out'), ('held', 'Held for review'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payout', to='store.orderitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payouts', to='manager.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
