# Generated by Django 5.1.3 on 2026-06-29 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_merchantpayout_fee_rate_merchantpayout_net_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='merchantpayout',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='store.payoutbatch'),
        ),
    ]
