# Generated by Django 5.1.3 on 2026-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_product_paygo_credit_improvement_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygoapplication',
            name='applicant_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paygoapplication',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
